Drupal Library Basic theme
==========================
Dan Scott <dan@coffeecode.net>
v0.1, 2015-09-10

This theme is based on the Library One-Pager theme originally created by
influx.us and maintained on https://github.com/ao5357/One-Pager[Github].

It includes the following elements:

* modules/library_search: Defines a configurable library search block that
  can link to a catalogue and provide a search box for an arbitrary target.
* modules/office_hours/office_hours.theme.inc : Replaces the stock
  office_hours theming include with an in-place version that generates
  openingHours markup. TODO: move the theming function into the actual
  theme (but in my defence, it's over 100 lines long!)
* modules/schema_address : Modifies the HTML generated by the Addressfield
  module to include schema.org markup, without requiring the RDF or
  schemaorg modules to be active.
* themes/library_basic : Includes templates and theming functions for
  overriding email and telephone HTML output so that the appropriate
  schema.org property can be included and the output complies with
  tel: URI scheme.

Dependencies
------------

Module dependencies include:

* Addressfield
* jQuery update
* Office Hours
* Views 

View templates that you need to import include:

* themes/library_basic/address_view.block
* themes/library_basic/hours_view.block
* themes/library_basic/library_content_view.block

You need to create some content types as well: library_address, hours,
library_home, and library_content_block. TODO: Define these.
