<?php

/**
 * @file
 * Add schema.org support for compound fields from contributed modules.
 */

/**
 * Implements MODULE_preprocess_HOOK().
 */
function schema_address_preprocess_field(&$variables) {
  $element = $variables['element'];
  $field_name = $element['#field_name'];

  // Address field module integration.
  // if ($element['#field_type'] == 'addressfield' && $element['#formatter'] == 'addressfield_default' && !empty($element['#object']->rdf_mapping[$field_name]['predicates'])) {
  if ($element['#field_type'] == 'addressfield' && $element['#formatter'] == 'addressfield_default') {
    module_load_include('inc', 'schema_address', 'schema_address.addressfield');
    schema_address_field_preprocess_addressfield($variables);
  }

}
